function G_mat = G_mat(in1)
%G_MAT
%    G_MAT = G_MAT(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    01-Nov-2022 11:09:47

q2 = in1(2,:);
q3 = in1(3,:);
q4 = in1(4,:);
q5 = in1(5,:);
t2 = sin(q2);
t3 = cos(q3);
t4 = sin(q4);
t5 = cos(q4);
t6 = sin(q3);
t7 = cos(q2);
t8 = cos(q5);
t9 = sin(q5);
t10 = t3.*t4.*t7;
t11 = t5.*t6.*t7;
t12 = t10+t11;
t13 = t8.*t12.*2.943e-2;
t14 = t3.*t5.*t7;
t20 = t4.*t6.*t7;
t15 = t14-t20;
t16 = t9.*t15.*2.943e-2;
t17 = t3.*t5.*t7.*2.3457672e-1;
t18 = t3.*t4.*t7.*7.95591e-1;
t19 = t5.*t6.*t7.*7.95591e-1;
G_mat = [0.0;t2.*2.943e-2+t7.*1.702035e-1+t2.*t3.*3.40407+t8.*(t2.*t3.*t5-t2.*t4.*t6).*2.943e-2-t9.*(t2.*t3.*t4+t2.*t5.*t6).*2.943e-2-t2.*t3.*t4.*2.3457672e-1+t2.*t3.*t5.*7.95591e-1-t2.*t4.*t6.*7.95591e-1-t2.*t5.*t6.*2.3457672e-1;t13+t16+t17+t18+t19+t6.*t7.*3.40407-t4.*t6.*t7.*2.3457672e-1;t13+t16+t17+t18+t19-t4.*t6.*t7.*2.3457672e-1;t13+t16];
